version: "2"

run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly

linters:
  settings:
      revive:
        rules:
          - name: exported
            severity: warning
            arguments: [ "disableStutteringCheck" ]
          - name: if-return
          - name: early-return
          - name: indent-error-flow
      gocyclo:
        min-complexity: 18
      dupl:
        threshold: 120
      misspell:
        locale: US
      errcheck:
        exclude-functions:
          - (*net/http.Server).Shutdown
      gosec:
        excludes:
          - G114 
          - G115 
          - G404
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
    - unparam
    - gocritic
    - whitespace
    - durationcheck
    - bodyclose
    - prealloc
    - gocyclo
    - dupl
    - gosec                 


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
