apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sms-api-pdb
spec:
  maxUnavailable: 1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sms-worker-pdb
spec:
  minAvailable: 1
