apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sms

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - configmap.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - hpa-api.yaml
